version: '3.8'

services:
  backend:
    build: .
    container_name: logiq-ai-backend
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - PORT=8000
      - DB_PATH=data/logiq.db
      - LOG_PATH=logs/queries.log
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    image: python:3.10-slim
    container_name: logiq-ai-frontend
    working_dir: /app
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
    volumes:
      - ./frontend:/app/frontend
      - ./requirements.txt:/app/requirements.txt
    command: >
      sh -c "pip install streamlit requests &&
             cd frontend &&
             streamlit run streamlit_app.py --server.port 8501 --server.address 0.0.0.0"
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    name: logiq-ai-network
